#!/usr/bin/env bash
# Installs nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
