#!/usr/bin/env bash
# This script tells a story of the "/etc/passwd" file
while IFS=: read -r f{1..7}; do
	echo The user "${f1:=}" is part of the "${f4:=}" gang, lives\
 in "${f6:=}" and rides "${f7:=}". "${f3:=}"\'s place is protected by the\
 passcode "${f2:=}", more info about the user here: "${f5:=}"
done < /etc/passwd
